/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eclipsesource_v8_V8API */

#ifndef _Included_com_eclipsesource_v8_V8API
#define _Included_com_eclipsesource_v8_V8API
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eclipsesource_v8_V8API_NULL
#define com_eclipsesource_v8_V8API_NULL 0L
#undef com_eclipsesource_v8_V8API_UNKNOWN
#define com_eclipsesource_v8_V8API_UNKNOWN 0L
#undef com_eclipsesource_v8_V8API_INTEGER
#define com_eclipsesource_v8_V8API_INTEGER 1L
#undef com_eclipsesource_v8_V8API_INT_32_ARRAY
#define com_eclipsesource_v8_V8API_INT_32_ARRAY 1L
#undef com_eclipsesource_v8_V8API_DOUBLE
#define com_eclipsesource_v8_V8API_DOUBLE 2L
#undef com_eclipsesource_v8_V8API_FLOAT_64_ARRAY
#define com_eclipsesource_v8_V8API_FLOAT_64_ARRAY 2L
#undef com_eclipsesource_v8_V8API_BOOLEAN
#define com_eclipsesource_v8_V8API_BOOLEAN 3L
#undef com_eclipsesource_v8_V8API_STRING
#define com_eclipsesource_v8_V8API_STRING 4L
#undef com_eclipsesource_v8_V8API_V8_ARRAY
#define com_eclipsesource_v8_V8API_V8_ARRAY 5L
#undef com_eclipsesource_v8_V8API_V8_OBJECT
#define com_eclipsesource_v8_V8API_V8_OBJECT 6L
#undef com_eclipsesource_v8_V8API_V8_FUNCTION
#define com_eclipsesource_v8_V8API_V8_FUNCTION 7L
#undef com_eclipsesource_v8_V8API_V8_TYPED_ARRAY
#define com_eclipsesource_v8_V8API_V8_TYPED_ARRAY 8L
#undef com_eclipsesource_v8_V8API_BYTE
#define com_eclipsesource_v8_V8API_BYTE 9L
#undef com_eclipsesource_v8_V8API_INT_8_ARRAY
#define com_eclipsesource_v8_V8API_INT_8_ARRAY 9L
#undef com_eclipsesource_v8_V8API_V8_ARRAY_BUFFER
#define com_eclipsesource_v8_V8API_V8_ARRAY_BUFFER 10L
#undef com_eclipsesource_v8_V8API_UNSIGNED_INT_8_ARRAY
#define com_eclipsesource_v8_V8API_UNSIGNED_INT_8_ARRAY 11L
#undef com_eclipsesource_v8_V8API_UNSIGNED_INT_8_CLAMPED_ARRAY
#define com_eclipsesource_v8_V8API_UNSIGNED_INT_8_CLAMPED_ARRAY 12L
#undef com_eclipsesource_v8_V8API_INT_16_ARRAY
#define com_eclipsesource_v8_V8API_INT_16_ARRAY 13L
#undef com_eclipsesource_v8_V8API_UNSIGNED_INT_16_ARRAY
#define com_eclipsesource_v8_V8API_UNSIGNED_INT_16_ARRAY 14L
#undef com_eclipsesource_v8_V8API_UNSIGNED_INT_32_ARRAY
#define com_eclipsesource_v8_V8API_UNSIGNED_INT_32_ARRAY 15L
#undef com_eclipsesource_v8_V8API_FLOAT_32_ARRAY
#define com_eclipsesource_v8_V8API_FLOAT_32_ARRAY 16L
#undef com_eclipsesource_v8_V8API_UNDEFINED
#define com_eclipsesource_v8_V8API_UNDEFINED 99L
/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _acquireLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1acquireLock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _releaseLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1releaseLock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _lowMemoryNotification
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1lowMemoryNotification
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _releaseRuntime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1releaseRuntime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _createIsolate
 * Signature: (Lcom/eclipsesource/v8/V8;)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1createIsolate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _createContext
 * Signature: (Lcom/eclipsesource/v8/V8Context;JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1createContext
  (JNIEnv *, jobject, jobject, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getBuildID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1getBuildID
  (JNIEnv *, jobject);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Object
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Object
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initEmptyContainer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initEmptyContainer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _createTwin
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1createTwin
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeIntegerScript
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1executeIntegerScript
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeDoubleScript
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_eclipsesource_v8_V8API__1executeDoubleScript
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeStringScript
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8API__1executeStringScript
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeBooleanScript
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1executeBooleanScript
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeScript
 * Signature: (JILjava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8API__1executeScript
  (JNIEnv *, jobject, jlong, jint, jstring, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeVoidScript
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1executeVoidScript
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _release
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1release
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _releaseMethodDescriptor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1releaseMethodDescriptor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _contains
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1contains
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getKeys
 * Signature: (JJ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_eclipsesource_v8_V8API__1getKeys
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getInteger
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1getInteger
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getBoolean
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1getBoolean
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getDouble
 * Signature: (JJLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_eclipsesource_v8_V8API__1getDouble
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getString
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8API__1getString
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _get
 * Signature: (JIJLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8API__1get
  (JNIEnv *, jobject, jlong, jint, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeIntegerFunction
 * Signature: (JJLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1executeIntegerFunction
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeDoubleFunction
 * Signature: (JJLjava/lang/String;J)D
 */
JNIEXPORT jdouble JNICALL Java_com_eclipsesource_v8_V8API__1executeDoubleFunction
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeStringFunction
 * Signature: (JJLjava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8API__1executeStringFunction
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeBooleanFunction
 * Signature: (JJLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1executeBooleanFunction
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeFunction
 * Signature: (JIJLjava/lang/String;J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8API__1executeFunction__JIJLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jint, jlong, jstring, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeFunction
 * Signature: (JJJJ)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8API__1executeFunction__JJJJ
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _executeVoidFunction
 * Signature: (JJLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1executeVoidFunction
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _equals
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1equals
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _toString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8API__1toString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _strictEquals
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1strictEquals
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _sameValue
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1sameValue
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _identityHash
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1identityHash
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _add
 * Signature: (JJLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1add__JJLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jlong, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addObject
 * Signature: (JJLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addObject
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _add
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1add__JJLjava_lang_String_2Z
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _add
 * Signature: (JJLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1add__JJLjava_lang_String_2D
  (JNIEnv *, jobject, jlong, jlong, jstring, jdouble);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _add
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1add__JJLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addUndefined
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addUndefined
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addNull
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addNull
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _registerJavaMethod
 * Signature: (JJLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1registerJavaMethod
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Array
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Array
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Function
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Function
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetSize
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetInteger
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetInteger
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetBoolean
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetBoolean
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetByte
 * Signature: (JJI)B
 */
JNIEXPORT jbyte JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetByte
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetDouble
 * Signature: (JJI)D
 */
JNIEXPORT jdouble JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetDouble
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetString
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetString
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGet
 * Signature: (JIJI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8API__1arrayGet
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addArrayIntItem
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addArrayIntItem
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addArrayBooleanItem
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addArrayBooleanItem
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addArrayDoubleItem
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addArrayDoubleItem
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addArrayStringItem
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addArrayStringItem
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addArrayObjectItem
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addArrayObjectItem
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addArrayUndefinedItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addArrayUndefinedItem
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _addArrayNullItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1addArrayNullItem
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getType
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1getType__JJLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getType
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1getType__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getArrayType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1getArrayType
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _setPrototype
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1setPrototype
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getConstructorName
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8API__1getConstructorName
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1getType__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getType
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1getType__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetDoubles
 * Signature: (JJII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetDoubles__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetIntegers
 * Signature: (JJII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetIntegers__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetBooleans
 * Signature: (JJII)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetBooleans__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetBytes
 * Signature: (JJII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetBytes__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetStrings
 * Signature: (JJII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetStrings__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetIntegers
 * Signature: (JJII[I)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetIntegers__JJII_3I
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jintArray);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetDoubles
 * Signature: (JJII[D)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetDoubles__JJII_3D
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jdoubleArray);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetBooleans
 * Signature: (JJII[Z)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetBooleans__JJII_3Z
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jbooleanArray);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetBytes
 * Signature: (JJII[B)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetBytes__JJII_3B
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jbyteArray);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _arrayGetStrings
 * Signature: (JJII[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8API__1arrayGetStrings__JJII_3Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jobjectArray);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8ArrayBuffer
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8ArrayBuffer__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8ArrayBuffer
 * Signature: (JLjava/nio/ByteBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8ArrayBuffer__JLjava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Int32Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Int32Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8UInt32Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8UInt32Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Float32Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Float32Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Float64Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Float64Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Int16Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Int16Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8UInt16Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8UInt16Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8Int8Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8Int8Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8UInt8Array
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8UInt8Array
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _initNewV8UInt8ClampedArray
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1initNewV8UInt8ClampedArray
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _setWeak
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1setWeak
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _clearWeak
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1clearWeak
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _isWeak
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1isWeak
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _createV8ArrayBufferBackingStore
 * Signature: (JJI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8API__1createV8ArrayBufferBackingStore
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _terminateExecution
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1terminateExecution
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getGlobalObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_eclipsesource_v8_V8API__1getGlobalObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8API__1getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _setFlags
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1setFlags
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _isNodeCompatible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1isNodeCompatible
  (JNIEnv *, jclass);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _startNodeJS
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8API__1startNodeJS
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _pumpMessageLoop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1pumpMessageLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_eclipsesource_v8_V8API
 * Method:    _isRunning
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8API__1isRunning
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
